function report = assess_uv_plane_coverage(outInput, sol, varargin)
% assess_uv_plane_coverage
%
% Assess interferometric U-V plane coverage for:
%   1. The continuous OCP science-hold solution "sol"
%   2. One or more propagated "out" structures at formation OPD ~= 0
%
% This helper is designed to work directly with the outputs generated by
% Example_GEO_Formation_OPD, which stores:
%   - out.dr_rtn as Nx3 RTN histories in km
%   - out.opd as OPD histories in km
%   - out.star.phi0 / out.star.beta in rad
%   - sol.RTN as Nx3 RTN histories in km
%
% Example:
%   [out, sol] = Example_GEO_Formation_OPD(...);
%   report = assess_uv_plane_coverage(out, sol);
%
%   report = assess_uv_plane_coverage({out1, out2, out3}, [], ...
%       'OutLabels', {'case 1', 'case 2', 'case 3'});
%
% Name-value pairs:
%   'phi0_rad'           : target azimuth in RTN [rad]
%   'beta_rad'           : target elevation in RTN [rad]
%   'ZeroOPDTol_m'       : OPD-spread ~= 0 tolerance [m], default 0.05
%   'MaxSpreadAtZero_m'  : optional upper bound on accepted OPD spread [m],
%                          default inf
%   'PlotFigures'        : true/false, default true
%   'MirrorUV'           : plot conjugate-symmetric points, default true
%   'OutLabels'          : labels for multiple out cases
%
% Zero-OPD rule for out structures:
%   The function treats "formation OPD = 0" as the time samples where the
%   formation OPD spread is zero, or within ZeroOPDTol_m of zero.
%   If no sample satisfies that tolerance, the nearest minimum-spread
%   sample is used as a fallback.
%
% Output:
%   report.star          : target geometry and UV-frame unit vectors
%   report.ocp           : continuous UV-track assessment for sol
%   report.outCases(k)   : full-track and zero-OPD snapshot assessment

if nargin < 2
    sol = [];
end

p = inputParser;
p.addParameter('phi0_rad', [], @(x) isempty(x) || isscalar(x));
p.addParameter('beta_rad', [], @(x) isempty(x) || isscalar(x));
p.addParameter('ZeroOPDTol_m', 0.05, @(x) isscalar(x) && x >= 0);
p.addParameter('MaxSpreadAtZero_m', inf, @(x) isscalar(x) && x >= 0);
p.addParameter('PlotFigures', true, @(x) islogical(x) || isnumeric(x));
p.addParameter('MirrorUV', true, @(x) islogical(x) || isnumeric(x));
p.addParameter('OutLabels', {}, @(x) iscell(x) || isstring(x));
p.parse(varargin{:});
opts = p.Results;

outCell = local_normalize_out_input(outInput);
[phi0, beta] = local_resolve_star_angles(outCell, opts.phi0_rad, opts.beta_rad);
[~, ~, uHat, vHat, sHat] = local_compute_uv_track(zeros(3,1), phi0, beta);

report = struct();
report.star.phi0_rad = phi0;
report.star.beta_rad = beta;
report.star.phi0_deg = rad2deg(phi0);
report.star.beta_deg = rad2deg(beta);
report.star.u_hat = uHat;
report.star.v_hat = vHat;
report.star.s_hat = sHat;

labels = local_resolve_labels(numel(outCell), opts.OutLabels);
outReports = cell(1, numel(outCell));
for iCase = 1:numel(outCell)
    outReports{iCase} = local_analyze_out_case(outCell{iCase}, phi0, beta, labels{iCase}, opts);
end
if isempty(outReports)
    report.outCases = struct([]);
else
    report.outCases = [outReports{:}];
end

if ~isempty(sol)
    report.ocp = local_analyze_ocp_solution(sol, phi0, beta);
else
    report.ocp = [];
end

local_print_summary(report);

if opts.PlotFigures
    if ~isempty(report.ocp)
        local_plot_ocp_tracks(report.ocp, opts);
    end
    if ~isempty(report.outCases)
        local_plot_out_zero_samples(report.outCases, opts);
        local_plot_out_zero_selection(report.outCases);
    end
end

end

function outCell = local_normalize_out_input(outInput)
if isempty(outInput)
    outCell = {};
elseif iscell(outInput)
    outCell = outInput;
elseif isstruct(outInput)
    outCell = {outInput};
else
    error('outInput must be an out struct, a cell array of out structs, or [].');
end
end

function labels = local_resolve_labels(nCases, userLabels)
labels = cell(1, nCases);
if isempty(userLabels)
    for k = 1:nCases
        if nCases == 1
            labels{k} = 'out';
        else
            labels{k} = sprintf('out %d', k);
        end
    end
    return
end

userLabels = cellstr(userLabels);
if numel(userLabels) ~= nCases
    error('OutLabels must have one label per out case.');
end
labels = userLabels;
end

function [phi0, beta] = local_resolve_star_angles(outCell, phi0Override, betaOverride)
phi0 = phi0Override;
beta = betaOverride;

if ~isempty(phi0) && ~isempty(beta)
    return
end

if isempty(outCell)
    error(['phi0_rad and beta_rad are required when no out structure is ' ...
           'provided, because the target geometry cannot be inferred.']);
end

out0 = outCell{1};
if ~isfield(out0, 'star') || ~isfield(out0.star, 'phi0') || ~isfield(out0.star, 'beta')
    error(['Target geometry not found in out.star. Provide phi0_rad and ' ...
           'beta_rad explicitly.']);
end

if isempty(phi0)
    phi0 = out0.star.phi0;
end
if isempty(beta)
    beta = out0.star.beta;
end
end

function ocp = local_analyze_ocp_solution(sol, phi0, beta)
rtnCell = local_extract_rtn_cell(sol, 'sol');
track = local_build_track_summary(rtnCell, phi0, beta);

ocp = struct();
ocp.label = 'OCP solution';
ocp.t_s = sol.t(:);
ocp.t_hr = ocp.t_s/3600;
ocp.track = track;

if isfield(sol, 'OPD_km')
    ocp.opdMatrix_m = 1000 * sol.OPD_km;
else
    ocp.opdMatrix_m = local_build_opd_matrix_from_track(track);
end

ocp.meanOPD_m = mean(ocp.opdMatrix_m, 2);
ocp.rangeOPD_m = max(ocp.opdMatrix_m, [], 2) - min(ocp.opdMatrix_m, [], 2);
ocp.summary = local_build_matrix_summary(track.combinedUV_m, ocp.opdMatrix_m, []);
ocp.summary.timeSpan_s = ocp.t_s(end) - ocp.t_s(1);
ocp.summary.timeSpan_min = ocp.summary.timeSpan_s / 60;
ocp.summary.maxOPDSpread_m = max(ocp.rangeOPD_m);
ocp.summary.meanAbsFormationOPD_m = mean(abs(ocp.meanOPD_m));

if isfield(sol, 'success')
    ocp.success = sol.success;
else
    ocp.success = [];
end
end

function caseReport = local_analyze_out_case(outCase, phi0, beta, label, opts)
rtnCell = local_extract_rtn_cell(outCase, 'out');
track = local_build_track_summary(rtnCell, phi0, beta);
opdMatrix_m = local_extract_opd_matrix(outCase);

caseReport = struct();
caseReport.label = label;
caseReport.t_s = local_extract_time_vector(outCase, size(opdMatrix_m,1));
caseReport.t_hr = caseReport.t_s/3600;
caseReport.track = track;
caseReport.opdMatrix_m = opdMatrix_m;
caseReport.meanOPD_m = mean(opdMatrix_m, 2);
caseReport.rangeOPD_m = max(opdMatrix_m, [], 2) - min(opdMatrix_m, [], 2);

caseReport.zeroOPD = local_find_zero_opd_snapshots(caseReport, opts);
caseReport.summary = local_build_matrix_summary(track.combinedUV_m, opdMatrix_m, caseReport.zeroOPD);
end

function rtnCell = local_extract_rtn_cell(dataStruct, sourceName)
if ~isfield(dataStruct, 'RTN') && ~isfield(dataStruct, 'dr_rtn')
    error('No RTN history found in %s. Expected field RTN or dr_rtn.', sourceName);
end

if isfield(dataStruct, 'RTN')
    raw = dataStruct.RTN;
else
    raw = dataStruct.dr_rtn;
end

if iscell(raw)
    rtnCell = raw;
else
    rtnCell = {raw};
end
end

function t = local_extract_time_vector(outCase, nRows)
if isfield(outCase, 't') && ~isempty(outCase.t)
    t = outCase.t(:);
else
    t = (0:nRows-1).';
end
end

function opdMatrix_m = local_extract_opd_matrix(outCase)
if ~isfield(outCase, 'opd')
    error('The provided out structure does not contain an opd field.');
end

if iscell(outCase.opd)
    nCollectors = numel(outCase.opd);
    nRows = numel(outCase.opd{1});
    opdMatrix_m = zeros(nRows, nCollectors);
    for j = 1:nCollectors
        opdMatrix_m(:,j) = 1000 * outCase.opd{j}(:);
    end
else
    opdMatrix_m = 1000 * outCase.opd(:);
end
end

function track = local_build_track_summary(rtnCell, phi0, beta)
nCollectors = numel(rtnCell);
track = struct();
track.nCollectors = nCollectors;
track.collectors = repmat(struct(), 1, nCollectors);

allUV = [];
for j = 1:nCollectors
    rtn_km = rtnCell{j};
    if size(rtn_km, 2) ~= 3
        error('RTN history must be Nx3.');
    end

    rtn_m = (1000 * rtn_km).';
    [uv, opd_m, uHat, vHat, sHat] = local_compute_uv_track(rtn_m, phi0, beta);
    uv_m = uv.';
    radius_m = sqrt(sum(uv_m.^2, 2));

    track.collectors(j).uv_m = uv_m;
    track.collectors(j).opd_m = opd_m(:);
    track.collectors(j).radius_m = radius_m;
    track.collectors(j).coverageArea_m2 = local_convex_hull_area(uv_m);
    track.collectors(j).maxRadius_m = max(radius_m);
    track.collectors(j).minRadius_m = min(radius_m);
    track.collectors(j).u_hat = uHat;
    track.collectors(j).v_hat = vHat;
    track.collectors(j).s_hat = sHat;

    allUV = [allUV; uv_m]; %#ok<AGROW>
end

track.combinedUV_m = allUV;
track.combinedCoverageArea_m2 = local_convex_hull_area(allUV);
track.combinedRadius_m = sqrt(sum(allUV.^2, 2));
track.maxRadius_m = max(track.combinedRadius_m);
track.minRadius_m = min(track.combinedRadius_m);
track.meanRadius_m = mean(track.combinedRadius_m);
end

function zero = local_find_zero_opd_snapshots(caseReport, opts)
rangeOPD_m = caseReport.rangeOPD_m;
t_s = caseReport.t_s;

idx = find(rangeOPD_m <= opts.ZeroOPDTol_m);
if isfinite(opts.MaxSpreadAtZero_m)
    idx = idx(rangeOPD_m(idx) <= opts.MaxSpreadAtZero_m);
end
idx = local_remove_adjacent_duplicates(idx);

fallbackUsed = false;
if isempty(idx)
    [~, idxMin] = min(rangeOPD_m);
    idx = idxMin;
    fallbackUsed = true;
end

zero = struct();
zero.indices = idx(:);
zero.t_s = t_s(idx);
zero.t_hr = zero.t_s / 3600;
zero.meanOPD_m = caseReport.meanOPD_m(idx);
zero.rangeOPD_m = rangeOPD_m(idx);
zero.usedNearestApproachFallback = fallbackUsed;

nCollectors = caseReport.track.nCollectors;
zero.collectors = repmat(struct(), 1, nCollectors);
allUV = [];
allLabels = [];
for j = 1:nCollectors
    uv_m = caseReport.track.collectors(j).uv_m(idx, :);
    opd_m = caseReport.track.collectors(j).opd_m(idx);

    zero.collectors(j).uv_m = uv_m;
    zero.collectors(j).opd_m = opd_m;
    zero.collectors(j).radius_m = sqrt(sum(uv_m.^2, 2));

    allUV = [allUV; uv_m]; %#ok<AGROW>
    allLabels = [allLabels; j*ones(size(uv_m,1),1)]; %#ok<AGROW>
end

zero.combinedUV_m = allUV;
zero.collectorIndex = allLabels;
zero.coverageArea_m2 = local_convex_hull_area(allUV);
zero.maxRadius_m = max(sqrt(sum(allUV.^2, 2)));
zero.minRadius_m = min(sqrt(sum(allUV.^2, 2)));
zero.nSamples = numel(idx);
end

function idx = local_remove_adjacent_duplicates(idx)
idx = unique(idx(:));
if isempty(idx)
    return
end

keep = true(size(idx));
for k = 2:numel(idx)
    keep(k) = (idx(k) - idx(k-1)) > 1;
end
idx = idx(keep);
end

function opdMatrix_m = local_build_opd_matrix_from_track(track)
nCollectors = track.nCollectors;
nRows = numel(track.collectors(1).opd_m);
opdMatrix_m = zeros(nRows, nCollectors);
for j = 1:nCollectors
    opdMatrix_m(:,j) = track.collectors(j).opd_m(:);
end
end

function summary = local_build_matrix_summary(allUV_m, opdMatrix_m, zeroOPD)
summary = struct();
summary.nCollectors = size(opdMatrix_m, 2);
summary.nTimeSamples = size(opdMatrix_m, 1);
summary.coverageArea_m2 = local_convex_hull_area(allUV_m);
summary.maxRadius_m = max(sqrt(sum(allUV_m.^2, 2)));
summary.minRadius_m = min(sqrt(sum(allUV_m.^2, 2)));
summary.meanRadius_m = mean(sqrt(sum(allUV_m.^2, 2)));
summary.maxAbsCollectorOPD_m = max(abs(opdMatrix_m(:)));
summary.maxFormationSpread_m = max(max(opdMatrix_m, [], 2) - min(opdMatrix_m, [], 2));

if nargin >= 3 && ~isempty(zeroOPD)
    summary.zeroOPDCount = zeroOPD.nSamples;
    summary.zeroOPDCoverageArea_m2 = zeroOPD.coverageArea_m2;
    summary.zeroOPDMaxSpread_m = max(zeroOPD.rangeOPD_m);
else
    summary.zeroOPDCount = 0;
    summary.zeroOPDCoverageArea_m2 = [];
    summary.zeroOPDMaxSpread_m = [];
end
end

function local_print_summary(report)
fprintf('\nU-V plane coverage summary\n');
fprintf('  Star geometry: phi0 = %.3f deg, beta = %.3f deg\n', ...
    report.star.phi0_deg, report.star.beta_deg);

if ~isempty(report.ocp)
    fprintf('\nOCP solution\n');
    fprintf('  Coverage area      : %.3f m^2\n', report.ocp.summary.coverageArea_m2);
    fprintf('  Radius range       : [%.3f, %.3f] m\n', ...
        report.ocp.summary.minRadius_m, report.ocp.summary.maxRadius_m);
    fprintf('  Max OPD spread     : %.3f m\n', report.ocp.summary.maxOPDSpread_m);
    fprintf('  Mean |formation OPD| : %.3f m\n', report.ocp.summary.meanAbsFormationOPD_m);
end

for k = 1:numel(report.outCases)
    thisCase = report.outCases(k);
    fprintf('\n%s\n', thisCase.label);
    fprintf('  Full-track area    : %.3f m^2\n', thisCase.summary.coverageArea_m2);
    fprintf('  Zero-OPD samples   : %d\n', thisCase.summary.zeroOPDCount);
    fprintf('  Zero-OPD area      : %.3f m^2\n', thisCase.summary.zeroOPDCoverageArea_m2);
    fprintf('  Max zero-OPD spread: %.3f m\n', thisCase.summary.zeroOPDMaxSpread_m);
    if thisCase.zeroOPD.usedNearestApproachFallback
        fprintf('  Zero selection     : nearest-approach fallback used\n');
    end
end
fprintf('\n');
end

function local_plot_ocp_tracks(ocp, opts)
colors = lines(ocp.track.nCollectors);
figure('Name', 'OCP U-V Coverage');
hold on
axis equal
grid on

for j = 1:ocp.track.nCollectors
    uv_m = ocp.track.collectors(j).uv_m;
    plot(uv_m(:,1), uv_m(:,2), 'LineWidth', 1.5, ...
        'Color', colors(j,:), 'DisplayName', sprintf('Collector %d', j));

    if opts.MirrorUV
        plot(-uv_m(:,1), -uv_m(:,2), '--', 'LineWidth', 1.0, ...
            'Color', colors(j,:), 'HandleVisibility', 'off');
    end
end

xlabel('u [m]');
ylabel('v [m]');
title('OCP science-hold U-V plane coverage');
legend('Location', 'best');
end

function local_plot_out_zero_samples(outCases, opts)
colors = lines(max(numel(outCases), 1));
markers = {'o', 's', '^', 'd', 'v', '>', '<', 'p', 'h'};

figure('Name', 'Zero-OPD U-V Samples');
hold on
axis equal
grid on

for iCase = 1:numel(outCases)
    for j = 1:outCases(iCase).track.nCollectors
        uv_m = outCases(iCase).zeroOPD.collectors(j).uv_m;
        if isempty(uv_m)
            continue
        end

        marker = markers{mod(j-1, numel(markers)) + 1};
        scatter(uv_m(:,1), uv_m(:,2), 45, ...
            'Marker', marker, ...
            'MarkerEdgeColor', colors(iCase,:), ...
            'DisplayName', sprintf('%s - C%d', outCases(iCase).label, j));

        if opts.MirrorUV
            scatter(-uv_m(:,1), -uv_m(:,2), 35, ...
                'Marker', marker, ...
                'MarkerEdgeColor', colors(iCase,:), ...
                'MarkerFaceColor', 'none', ...
                'HandleVisibility', 'off');
        end
    end
end

xlabel('u [m]');
ylabel('v [m]');
title('U-V samples at formation OPD \approx 0');
legend('Location', 'bestoutside');
end

function local_plot_out_zero_selection(outCases)
nCases = numel(outCases);
figure('Name', 'Zero-OPD Selection');
tiledlayout(nCases, 1, 'TileSpacing', 'compact');

for iCase = 1:nCases
    nexttile
    plot(outCases(iCase).t_hr, outCases(iCase).rangeOPD_m, 'color','k','LineWidth', 1.3);
    hold on
    yline(0, '--k');

    idx = outCases(iCase).zeroOPD.indices;

    plot(outCases(iCase).t_hr(idx), outCases(iCase).rangeOPD_m(idx), ...
        'ro', 'MarkerFaceColor', 'r', 'DisplayName', 'selected');

    colororder('b')

    yyaxis right
    plot(outCases(iCase).t_hr, outCases(iCase).meanOPD_m, '--', 'LineWidth', 1.0);
    ylabel('Mean OPD [m]');

    yyaxis left
    ylabel('OPD spread [m]');
    xlabel('Time [hr]');
    title(sprintf('%s: OPD-spread-zero snapshot selection', outCases(iCase).label));
    grid on
end
end

function area = local_convex_hull_area(points)
if isempty(points) || size(points,1) < 3
    area = 0;
    return
end

points = unique(points, 'rows');
if size(points,1) < 3
    area = 0;
    return
end

try
    k = convhull(points(:,1), points(:,2));
    area = polyarea(points(k,1), points(k,2));
catch
    area = 0;
end
end

function [uv, opd, u_hat, v_hat, s_hat] = local_compute_uv_track(rtn_m, phi0_rad, beta_rad)
s_hat = [cos(beta_rad)*cos(phi0_rad);
         cos(beta_rad)*sin(phi0_rad);
         sin(beta_rad)];

ref = [0; 0; 1];
if abs(dot(s_hat, ref)) > 0.98
    ref = [1; 0; 0];
end

u_hat = cross(ref, s_hat);
u_hat = u_hat / norm(u_hat);

v_hat = cross(s_hat, u_hat);
v_hat = v_hat / norm(v_hat);

opd = s_hat.' * rtn_m;
Bperp = rtn_m - s_hat * opd;
uv = [u_hat.' * Bperp;
      v_hat.' * Bperp];
end
